version: '3.7'
configs:
  jupyterhub_config:
    file: ./hub/jupyterhub_config.py
  cull_idle_config:
    file: ./hub/cull_idle_servers.py

services:
  jupyterhub:
    image: nielsbohr/jupyterhub:edge
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
       - "80:8000"
    environment:
      TZ: Europe/Copenhagen
      # Required when the 'auth_state' flag is enabled
      # means that the 'hub/setup_jup_crypt_secret.sh script
      # must be sources before the stack is deployed
      # https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html
      JUPYTERHUB_CRYPT_KEY: ${JUPYTERHUB_CRYPT_KEY}
    configs:
      # Mount both the config file for the jupyterhub server itself and the
      # script that kills idle containers. Furthermore the base-notebook
      # notebook image config must be mounted so that jupyterhub has access
      # to it
      - source: jupyterhub_config
        target: /etc/jupyterhub/jupyterhub_config.py
        mode: 0440
      - source: cull_idle_config
        target: /srv/jupyterhub/cull_idle_servers.py
        mode: 0440
    volumes:
      # The jupyterhub service needs accces to the docker daemon process
      # to launch addtional notebook services from within the service itself
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Keep the jhub states such as the db saved during restarts
      - type: volume
        source: jhubstate
        target: /srv/jupyterhub
    command: jupyterhub -f /etc/jupyterhub/jupyterhub_config.py
  docker-volume-monitor:
    image: nielsbohr/docker-volume-monitor:latest
    deploy:
      mode: global
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker-image-updater:
    image: nielsbohr/docker-image-updater:latest
    deploy:
      mode: global
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -update nielsbohr/base-notebook

volumes:
  jhubstate: